package com.szfp.szfp.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szfp.szfp.bean.AccountReportBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACCOUNT_REPORT_BEAN".
*/
public class AccountReportBeanDao extends AbstractDao<AccountReportBean, Long> {

    public static final String TABLENAME = "ACCOUNT_REPORT_BEAN";

    /**
     * Properties of entity AccountReportBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ACName = new Property(1, String.class, "ACName", false, "ACNAME");
        public final static Property ACNumber = new Property(2, String.class, "ACNumber", false, "ACNUMBER");
        public final static Property Deposits = new Property(3, float.class, "deposits", false, "DEPOSITS");
        public final static Property DepositsDate = new Property(4, long.class, "depositsDate", false, "DEPOSITS_DATE");
        public final static Property FarePaid = new Property(5, float.class, "farePaid", false, "FARE_PAID");
        public final static Property FarePaidDate = new Property(6, long.class, "farePaidDate", false, "FARE_PAID_DATE");
        public final static Property Balance = new Property(7, float.class, "balance", false, "BALANCE");
    }


    public AccountReportBeanDao(DaoConfig config) {
        super(config);
    }
    
    public AccountReportBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACCOUNT_REPORT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ACNAME\" TEXT," + // 1: ACName
                "\"ACNUMBER\" TEXT," + // 2: ACNumber
                "\"DEPOSITS\" REAL NOT NULL ," + // 3: deposits
                "\"DEPOSITS_DATE\" INTEGER NOT NULL ," + // 4: depositsDate
                "\"FARE_PAID\" REAL NOT NULL ," + // 5: farePaid
                "\"FARE_PAID_DATE\" INTEGER NOT NULL ," + // 6: farePaidDate
                "\"BALANCE\" REAL NOT NULL );"); // 7: balance
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACCOUNT_REPORT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AccountReportBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ACName = entity.getACName();
        if (ACName != null) {
            stmt.bindString(2, ACName);
        }
 
        String ACNumber = entity.getACNumber();
        if (ACNumber != null) {
            stmt.bindString(3, ACNumber);
        }
        stmt.bindDouble(4, entity.getDeposits());
        stmt.bindLong(5, entity.getDepositsDate());
        stmt.bindDouble(6, entity.getFarePaid());
        stmt.bindLong(7, entity.getFarePaidDate());
        stmt.bindDouble(8, entity.getBalance());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AccountReportBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ACName = entity.getACName();
        if (ACName != null) {
            stmt.bindString(2, ACName);
        }
 
        String ACNumber = entity.getACNumber();
        if (ACNumber != null) {
            stmt.bindString(3, ACNumber);
        }
        stmt.bindDouble(4, entity.getDeposits());
        stmt.bindLong(5, entity.getDepositsDate());
        stmt.bindDouble(6, entity.getFarePaid());
        stmt.bindLong(7, entity.getFarePaidDate());
        stmt.bindDouble(8, entity.getBalance());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AccountReportBean readEntity(Cursor cursor, int offset) {
        AccountReportBean entity = new AccountReportBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ACName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ACNumber
            cursor.getFloat(offset + 3), // deposits
            cursor.getLong(offset + 4), // depositsDate
            cursor.getFloat(offset + 5), // farePaid
            cursor.getLong(offset + 6), // farePaidDate
            cursor.getFloat(offset + 7) // balance
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AccountReportBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setACName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setACNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDeposits(cursor.getFloat(offset + 3));
        entity.setDepositsDate(cursor.getLong(offset + 4));
        entity.setFarePaid(cursor.getFloat(offset + 5));
        entity.setFarePaidDate(cursor.getLong(offset + 6));
        entity.setBalance(cursor.getFloat(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AccountReportBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AccountReportBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AccountReportBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
