package com.szfp.szfp.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.szfp.szfp.bean.VehicleInfoBean;
import com.szfp.szfp.bean.CommuterAccountInfoBean;
import com.szfp.szfp.bean.BankRegistrationBean;
import com.szfp.szfp.bean.BankCustomerBean;
import com.szfp.szfp.bean.StudentBean;
import com.szfp.szfp.bean.AccountReportBean;

import com.szfp.szfp.greendao.VehicleInfoBeanDao;
import com.szfp.szfp.greendao.CommuterAccountInfoBeanDao;
import com.szfp.szfp.greendao.BankRegistrationBeanDao;
import com.szfp.szfp.greendao.BankCustomerBeanDao;
import com.szfp.szfp.greendao.StudentBeanDao;
import com.szfp.szfp.greendao.AccountReportBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig vehicleInfoBeanDaoConfig;
    private final DaoConfig commuterAccountInfoBeanDaoConfig;
    private final DaoConfig bankRegistrationBeanDaoConfig;
    private final DaoConfig bankCustomerBeanDaoConfig;
    private final DaoConfig studentBeanDaoConfig;
    private final DaoConfig accountReportBeanDaoConfig;

    private final VehicleInfoBeanDao vehicleInfoBeanDao;
    private final CommuterAccountInfoBeanDao commuterAccountInfoBeanDao;
    private final BankRegistrationBeanDao bankRegistrationBeanDao;
    private final BankCustomerBeanDao bankCustomerBeanDao;
    private final StudentBeanDao studentBeanDao;
    private final AccountReportBeanDao accountReportBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        vehicleInfoBeanDaoConfig = daoConfigMap.get(VehicleInfoBeanDao.class).clone();
        vehicleInfoBeanDaoConfig.initIdentityScope(type);

        commuterAccountInfoBeanDaoConfig = daoConfigMap.get(CommuterAccountInfoBeanDao.class).clone();
        commuterAccountInfoBeanDaoConfig.initIdentityScope(type);

        bankRegistrationBeanDaoConfig = daoConfigMap.get(BankRegistrationBeanDao.class).clone();
        bankRegistrationBeanDaoConfig.initIdentityScope(type);

        bankCustomerBeanDaoConfig = daoConfigMap.get(BankCustomerBeanDao.class).clone();
        bankCustomerBeanDaoConfig.initIdentityScope(type);

        studentBeanDaoConfig = daoConfigMap.get(StudentBeanDao.class).clone();
        studentBeanDaoConfig.initIdentityScope(type);

        accountReportBeanDaoConfig = daoConfigMap.get(AccountReportBeanDao.class).clone();
        accountReportBeanDaoConfig.initIdentityScope(type);

        vehicleInfoBeanDao = new VehicleInfoBeanDao(vehicleInfoBeanDaoConfig, this);
        commuterAccountInfoBeanDao = new CommuterAccountInfoBeanDao(commuterAccountInfoBeanDaoConfig, this);
        bankRegistrationBeanDao = new BankRegistrationBeanDao(bankRegistrationBeanDaoConfig, this);
        bankCustomerBeanDao = new BankCustomerBeanDao(bankCustomerBeanDaoConfig, this);
        studentBeanDao = new StudentBeanDao(studentBeanDaoConfig, this);
        accountReportBeanDao = new AccountReportBeanDao(accountReportBeanDaoConfig, this);

        registerDao(VehicleInfoBean.class, vehicleInfoBeanDao);
        registerDao(CommuterAccountInfoBean.class, commuterAccountInfoBeanDao);
        registerDao(BankRegistrationBean.class, bankRegistrationBeanDao);
        registerDao(BankCustomerBean.class, bankCustomerBeanDao);
        registerDao(StudentBean.class, studentBeanDao);
        registerDao(AccountReportBean.class, accountReportBeanDao);
    }
    
    public void clear() {
        vehicleInfoBeanDaoConfig.clearIdentityScope();
        commuterAccountInfoBeanDaoConfig.clearIdentityScope();
        bankRegistrationBeanDaoConfig.clearIdentityScope();
        bankCustomerBeanDaoConfig.clearIdentityScope();
        studentBeanDaoConfig.clearIdentityScope();
        accountReportBeanDaoConfig.clearIdentityScope();
    }

    public VehicleInfoBeanDao getVehicleInfoBeanDao() {
        return vehicleInfoBeanDao;
    }

    public CommuterAccountInfoBeanDao getCommuterAccountInfoBeanDao() {
        return commuterAccountInfoBeanDao;
    }

    public BankRegistrationBeanDao getBankRegistrationBeanDao() {
        return bankRegistrationBeanDao;
    }

    public BankCustomerBeanDao getBankCustomerBeanDao() {
        return bankCustomerBeanDao;
    }

    public StudentBeanDao getStudentBeanDao() {
        return studentBeanDao;
    }

    public AccountReportBeanDao getAccountReportBeanDao() {
        return accountReportBeanDao;
    }

}
